services:
  - name: auth-service
    type: web
    runtime: go
    plan: free
    buildCommand: go build -o bin/auth cmd/main.go
    startCommand: ./bin/auth
    envVars:
      - key: GO_VERSION
        value: 1.24.1
      - key: GOTOOLCHAIN
        value: auto
      - key: PORT
        value: 8080
