server:
  port: ":8080"
mongodb:
  uri: "mongodb://localhost:27017"
  database: "auth_service"
neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "password"
firebase:
  credentials_path: "../secrets/serviceAccountKey.json"
